const statusUrl="boot-watch-status.json";
const logsUrl="boot-watch-logs.json";
const runsUrl="boot-watch-runs.json";
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function repairJsonText(t){return String(t||"").replace(/},\\n\s*{/g,"},{").replace(/},\\n\s*\]/g,"}\n]");}
function decodeB64(v){try{const raw=atob(v||"");const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return new TextDecoder("utf-8").decode(bytes);}catch(e){try{return atob(v||"");}catch(e2){return "[decode failed] "+e2;}}}
function loadJson(url,fallback){return fetch(url,{cache:"no-store"}).then(r=>r.text()).then(t=>{try{return JSON.parse(t);}catch(e){try{return JSON.parse(repairJsonText(t));}catch(e2){fallback._error=String(e2||e);return fallback;}}}).catch(e=>{fallback._error=String(e);return fallback;});}
function statusClass(v){v=String(v||"").toUpperCase();if(v==="PASS"||v==="YES"||v==="OK")return"good";if(v==="FAIL"||v==="NO")return"bad";return"muted";}
function card(label,value,cls=""){return `<div class="card"><div class="label">${esc(label)}</div><div class="value ${cls}">${esc(value??"-")}</div></div>`;}
function badge(text,cls="muted"){return `<span class="badge ${cls}">${esc(text)}</span>`;}
function logText(l){if(l.content_b64)return decodeB64(l.content_b64);return String(l.content||"").replaceAll("\\n","\n");}
function setTabs(){ $$(".tab").forEach(b=>b.addEventListener("click",()=>{ $$(".tab").forEach(x=>x.classList.remove("active")); $$(".tabPanel").forEach(x=>x.classList.remove("active")); b.classList.add("active"); $("#"+b.dataset.tab).classList.add("active"); })); }
function renderStatus(d){const result=d.pbw_result||"unknown";$("#statusBadge").className="badge "+statusClass(result);$("#statusBadge").textContent=result;$("#lastRefresh").textContent=d.bw_webui_generated||d.pbw_generated||"not generated";$("#quickCards").innerHTML=[card("Result",result),card("Mode",d.pbw_mode),card("Run ID",d.pbw_run_id),card("WebUI scope",d.bw_webui_scope),card("No host run",d.bw_webui_no_host_run),card("No route change",d.bw_webui_no_route_change)].join("");const keys=["pbw_version","pbw_versionCode","pbw_result_path","pbw_last_result_path","pbw_action_result_path","pbw_archive_path","pbw_status_env_path","bw_webui_source","bw_webui_generated"];$("#overviewTable").innerHTML=`<table>${keys.map(k=>`<tr><td>${esc(k)}</td><td>${esc(d[k]||"")}</td></tr>`).join("")}</table>`;const safe=[["Scope",d.bw_webui_scope==="bootwatch_only"],["No shell",d.bw_webui_no_shell==="yes"],["No host run",d.bw_webui_no_host_run==="yes"],["No route change",d.bw_webui_no_route_change==="yes"]];$("#safetyGrid").innerHTML=safe.map(x=>card(x[0],x[1]?"PASS":"CHECK",x[1]?"good":"warn")).join("");}
let allLogs=[];
function renderLogs(d){allLogs=d.logs||[];$("#logSummary").textContent=`${allLogs.length} log entries exported`+(d._error?` · ${d._error}`:"");applyLogFilter();}
function logRow(l,i){const text=logText(l);const exists=String(l.exists||"");const ok=exists==="yes"||exists==="true";return `<details class="log" ${i===0?"open":""} data-haystack="${esc((l.label||"")+" "+(l.path||"")+" "+text)}"><summary><span class="logTitle"><strong>${esc(l.label||"Log")}</strong>${badge(ok?"present":exists,statusClass(ok?"PASS":exists))}</span><span class="logMeta">${esc(l.size)} bytes · ${esc(l.mtime)}</span></summary><div class="path">${esc(l.path)}</div><div class="logActions"><button class="copyBtn" data-copy="${i}" type="button">Copy text</button></div><pre>${esc(text)}</pre></details>`;}
function applyLogFilter(){const q=($("#logSearch")?.value||"").toLowerCase().trim();const rows=allLogs.map((l,i)=>({l,i,t:((l.label||"")+" "+(l.path||"")+" "+logText(l)).toLowerCase()})).filter(x=>!q||x.t.includes(q));$("#logsList").innerHTML=rows.map(x=>logRow(x.l,x.i)).join("")||`<div class="card">No matching logs.</div>`;$$(".copyBtn").forEach(b=>b.addEventListener("click",async()=>{const t=logText(allLogs[Number(b.dataset.copy)]||{});try{await navigator.clipboard.writeText(t);b.textContent="Copied";}catch(e){b.textContent="Copy failed";}setTimeout(()=>b.textContent="Copy text",1200);}));}
function renderRuns(d){const runs=d.runs||[];$("#runSummary").textContent=`${runs.length} runs exported`+(d._error?` · ${d._error}`:"");$("#runsList").innerHTML=runs.map(r=>`<div class="run card"><div class="logTitle"><strong>${esc(r.run_id)}</strong>${badge(r.result,statusClass(r.result))}${badge(r.mode)}</div><div class="logMeta">${esc(r.mtime)} · ${esc(r.size)} bytes</div><code>${esc(r.path)}</code></div>`).join("")||`<div class="card">No run history exported yet.</div>`;}
setTabs();
$("#logSearch").addEventListener("input",applyLogFilter);
$("#expandAll").addEventListener("click",()=>$$('#logsList details').forEach(d=>d.open=true));
$("#collapseAll").addEventListener("click",()=>$$('#logsList details').forEach(d=>d.open=false));
Promise.all([loadJson(statusUrl,{}),loadJson(logsUrl,{logs:[]}),loadJson(runsUrl,{runs:[]})]).then(v=>{renderStatus(v[0]);renderLogs(v[1]);renderRuns(v[2]);}).catch(err=>{document.body.innerHTML="<pre>Boot Watch WebUI load failed: "+esc(err)+"</pre>";});
